export const idiomas = {
    es: {
      nombre: 'Español',
      bandera: '🇪🇸',
      nav: {
        grupos: '📊 Grupos',
        fixture: '📅 Fixture',
        eliminatoria: '🏆 Eliminatoria',
        bracket: '📊 Bracket',
      },
      grupos: {
        titulo: '⚽ Fase de Grupos',
        equipo: 'Equipo',
        pj: 'PJ', g: 'G', e: 'E', p: 'P', gf: 'GF', gc: 'GC', dif: 'Dif', pts: 'Pts',
        clasificados: 'La línea azul indica los equipos clasificados a 16vos de final',
      },
      fixture: {
        titulo: '📅 Fixture',
        editar: '✏️ Editar resultado',
        guardar: '✅ Guardar',
      },
      eliminatoria: {
        titulo: '🏆 Fase Eliminatoria',
        subtitulo: 'Edita cada partido para ingresar equipos y resultados',
        copaTitulo: 'COPA MUNDIAL FIFA 2026',
        dieciseisavos: '⚔️ Dieciseisavos de Final',
        octavos: '🔥 Octavos de Final',
        cuartos: '⭐ Cuartos de Final',
        semis: '🌟 Semifinales',
        tercero: '🥉 Tercer Puesto',
        final: '🏆 Gran Final',
        editar: '✏️ Editar',
        listo: '✅ Listo',
        local: 'Equipo local',
        visita: 'Equipo visita',
      },
      bracket: {
        titulo: '🏆 Bracket',
        subtitulo: 'Desliza o usa las flechas para navegar',
        dieciseisavos: '16avos',
        octavos: 'Octavos',
        cuartos: 'Cuartos',
        semis: 'Semifinal',
        final: 'FINAL',
        tercero: '🥉 3er Puesto',
      },
      header: {
        subtitulo: 'USA · México · Canadá',
        claro: '☀️ Claro',
        oscuro: '🌙 Oscuro',
        idioma: '🌐 Idioma',
      },
    },
    en: {
      nombre: 'English',
      bandera: '🇬🇧',
      nav: {
        grupos: '📊 Groups',
        fixture: '📅 Schedule',
        eliminatoria: '🏆 Knockout',
        bracket: '📊 Bracket',
      },
      grupos: {
        titulo: '⚽ Group Stage',
        equipo: 'Team',
        pj: 'MP', g: 'W', e: 'D', p: 'L', gf: 'GF', gc: 'GA', dif: 'GD', pts: 'Pts',
        clasificados: 'Blue line indicates teams qualified for Round of 32',
      },
      fixture: {
        titulo: '📅 Schedule',
        editar: '✏️ Edit result',
        guardar: '✅ Save',
      },
      eliminatoria: {
        titulo: '🏆 Knockout Stage',
        subtitulo: 'Edit each match to enter teams and results',
        copaTitulo: 'FIFA WORLD CUP 2026',
        dieciseisavos: '⚔️ Round of 32',
        octavos: '🔥 Round of 16',
        cuartos: '⭐ Quarter Finals',
        semis: '🌟 Semi Finals',
        tercero: '🥉 Third Place',
        final: '🏆 Grand Final',
        editar: '✏️ Edit',
        listo: '✅ Done',
        local: 'Home team',
        visita: 'Away team',
      },
      bracket: {
        titulo: '🏆 Bracket',
        subtitulo: 'Swipe or use arrows to navigate',
        dieciseisavos: 'R32',
        octavos: 'R16',
        cuartos: 'QF',
        semis: 'SF',
        final: 'FINAL',
        tercero: '🥉 3rd Place',
      },
      header: {
        subtitulo: 'USA · Mexico · Canada',
        claro: '☀️ Light',
        oscuro: '🌙 Dark',
        idioma: '🌐 Language',
      },
    },
  };
  
  export const idiomasDisponibles = ['es', 'en'];